#include "bluetooth_service.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <pthread.h>

/* ── Internal device list ────────────────────────────────────────────── */

static BtDevice g_devices[BT_MAX_DEVICES];
static size_t g_device_count = 0;
static int g_power = 0;

/* ── Background scan state ───────────────────────────────────────────── */
static volatile int g_scan_running = 0;
static pthread_t    g_scan_thread;

/* ── Subprocess helper ───────────────────────────────────────────────── */

/* Run a bluetoothctl command and capture up to out_sz-1 bytes of output.
 * Returns 0 on success, -1 on failure. out may be NULL if you don't need output. */
static int btctl(const char *cmd, char *out, size_t out_sz)
{
    char full[256];
    /* timeout 3: prevents any bluetoothctl call from blocking the UI thread
     * if bluetoothd is not running or not responding on D-Bus. */
    snprintf(full, sizeof(full), "timeout 3 bluetoothctl %s 2>/dev/null", cmd);

    FILE *f = popen(full, "r");
    if (!f)
        return -1;

    if (out && out_sz > 0)
    {
        size_t total = 0;
        char line[256];
        while (fgets(line, sizeof(line), f) && total + strlen(line) < out_sz - 1)
        {
            strcat(out + total, line);
            total += strlen(line);
        }
    }

    int rc = pclose(f);
    return (rc == 0) ? 0 : -1;
}

/* ── Audio routing ───────────────────────────────────────────────────── */

/* Called when a BT device with audio capability connects.
 * Rewrites /etc/asound.conf to route ALSA 'default' through bluealsa. */
static void asound_set_bt(const char *mac)
{
    FILE *f = fopen("/etc/asound.conf", "w");
    if (!f)
        return;
    fprintf(f,
            "# Generated by bluetooth_service — BT A2DP active\n"
            "pcm.!default {\n"
            "    type bluealsa\n"
            "    device \"%s\"\n"
            "    profile \"a2dp\"\n"
            "}\n"
            "ctl.!default {\n"
            "    type bluealsa\n"
            "}\n",
            mac);
    fclose(f);
}

/* Called when BT disconnects. Reads /tmp/bh-audio-card and restores
 * the USB card routing that rcS originally wrote. */
static void asound_restore_usb(void)
{
    int card = 1; /* fallback */
    FILE *cf = fopen("/tmp/bh-audio-card", "r");
    if (cf)
    {
        fscanf(cf, "%d", &card);
        fclose(cf);
    }

    FILE *f = fopen("/etc/asound.conf", "w");
    if (!f)
        return;
    fprintf(f,
            "# Generated by bluetooth_service — USB card %d\n"
            "pcm.!default {\n"
            "    type plug\n"
            "    slave.pcm \"hw:%d,0\"\n"
            "}\n"
            "ctl.!default {\n"
            "    type hw\n"
            "    card %d\n"
            "}\n",
            card, card, card);
    fclose(f);
}

/* ── Device info parser ──────────────────────────────────────────────── */

/* Parse a single field from "bluetoothctl info <mac>" output.
 * Looks for lines like "    FieldName: value" */
static void parse_info_field(const char *output, const char *field,
                             char *out, size_t out_sz)
{
    const char *p = output;
    char search[64];
    snprintf(search, sizeof(search), "\t%s: ", field);

    while ((p = strstr(p, search)) != NULL)
    {
        p += strlen(search);
        const char *end = strchr(p, '\n');
        size_t len = end ? (size_t)(end - p) : strlen(p);
        if (len >= out_sz)
            len = out_sz - 1;
        strncpy(out, p, len);
        out[len] = '\0';
        return;
    }
    out[0] = '\0';
}

/* Fill in a BtDevice struct by running "bluetoothctl info <mac>".
 * Returns 1 if the device has audio capability (A2DP or HFP UUIDs). */
static int fill_device_info(BtDevice *dev)
{
    char out[2048] = {0};
    char full[256];
    snprintf(full, sizeof(full), "timeout 3 bluetoothctl info %s 2>/dev/null", dev->mac);
    FILE *fp = popen(full, "r");
    if (!fp)
        return 0;
    size_t total = 0;
    char line[256];
    while (fgets(line, sizeof(line), fp) && total + strlen(line) < sizeof(out) - 1)
    {
        strcat(out + total, line);
        total += strlen(line);
    }
    pclose(fp);

    char val[64];

    parse_info_field(out, "Name", dev->name, sizeof(dev->name));
    if (dev->name[0] == '\0')
        strncpy(dev->name, dev->mac, sizeof(dev->name) - 1);

    parse_info_field(out, "Connected", val, sizeof(val));
    dev->connected = (strcmp(val, "yes") == 0);

    parse_info_field(out, "Paired", val, sizeof(val));
    dev->paired = (strcmp(val, "yes") == 0);

    parse_info_field(out, "Trusted", val, sizeof(val));
    dev->trusted = (strcmp(val, "yes") == 0);

    /* Audio capable = has A2DP Sink or Handsfree UUID */
    dev->audio_capable = (strstr(out, "0000110b") != NULL || /* A2DP Sink */
                          strstr(out, "0000111e") != NULL || /* Handsfree */
                          strstr(out, "00001108") != NULL);  /* Headset */
    return 1;
}

/* ── Public API ──────────────────────────────────────────────────────── */

void bluetooth_service_init(void)
{
    g_device_count = 0;
    g_power = 0;
}

void bluetooth_service_shutdown(void)
{
    g_device_count = 0;
}

int bluetooth_service_is_available(void)
{
    /* hci0 exists if the BT adapter is up */
    FILE *f = fopen("/sys/class/bluetooth/hci0", "r");
    if (f)
    {
        fclose(f);
        return 1;
    }
    /* sysfs entry is a directory, not a file — check with access() */
    return (access("/sys/class/bluetooth/hci0", F_OK) == 0) ? 1 : 0;
}

int bluetooth_service_set_power(int on)
{
    int rc = btctl(on ? "power on" : "power off", NULL, 0);
    if (rc == 0)
        g_power = on;
    return rc;
}

int bluetooth_service_get_power(void)
{
    char out[512] = {0};
    btctl("show", out, sizeof(out));
    if (strstr(out, "Powered: yes"))
    {
        g_power = 1;
        return 1;
    }
    g_power = 0;
    return 0;
}

/* Scan for 6 seconds then populate the internal device list. */
int bluetooth_service_refresh_devices(void)
{
    if (!g_power)
        return -1;

    /* Start scan, wait, stop scan */
    btctl("scan on", NULL, 0);
    sleep(6);
    btctl("scan off", NULL, 0);

    /* Collect MAC addresses from "bluetoothctl devices" */
    FILE *fp = popen("timeout 3 bluetoothctl devices 2>/dev/null", "r");
    if (!fp)
        return -1;

    g_device_count = 0;
    char line[256];
    while (fgets(line, sizeof(line), fp) && g_device_count < BT_MAX_DEVICES)
    {
        /* Format: "Device XX:XX:XX:XX:XX:XX Name Here" */
        if (strncmp(line, "Device ", 7) != 0)
            continue;
        char mac[24] = {0};
        if (sscanf(line + 7, "%23s", mac) != 1)
            continue;

        BtDevice *dev = &g_devices[g_device_count];
        memset(dev, 0, sizeof(BtDevice));
        strncpy(dev->mac, mac, sizeof(dev->mac) - 1);

        fill_device_info(dev);
        g_device_count++;
    }
    pclose(fp);
    return 0;
}

static void *scan_thread_fn(void *arg)
{
    (void)arg;
    btctl("scan on", NULL, 0);
    sleep(6);
    btctl("scan off", NULL, 0);

    FILE *fp = popen("timeout 3 bluetoothctl devices 2>/dev/null", "r");
    if (fp)
    {
        g_device_count = 0;
        char line[256];
        while (fgets(line, sizeof(line), fp) && g_device_count < BT_MAX_DEVICES)
        {
            if (strncmp(line, "Device ", 7) != 0)
                continue;
            char mac[24] = {0};
            if (sscanf(line + 7, "%23s", mac) != 1)
                continue;
            BtDevice *dev = &g_devices[g_device_count];
            memset(dev, 0, sizeof(BtDevice));
            strncpy(dev->mac, mac, sizeof(dev->mac) - 1);
            fill_device_info(dev);
            g_device_count++;
        }
        pclose(fp);
    }

    g_scan_running = 0;
    return NULL;
}

int bluetooth_service_scan_start(void)
{
    if (!g_power)
        return -1;
    if (g_scan_running)
        return 0;
    g_scan_running = 1;
    if (pthread_create(&g_scan_thread, NULL, scan_thread_fn, NULL) != 0)
    {
        g_scan_running = 0;
        return -1;
    }
    pthread_detach(g_scan_thread);
    return 0;
}

int bluetooth_service_scan_is_running(void)
{
    return g_scan_running;
}

size_t bluetooth_service_device_count(void)
{
    return g_device_count;
}

const BtDevice *bluetooth_service_device_at(size_t index)
{
    if (index >= g_device_count)
        return NULL;
    return &g_devices[index];
}

int bluetooth_service_connect(const char *mac)
{
    if (!mac)
        return -1;
    char cmd[64];

    /* Trust first so it auto-connects in future */
    snprintf(cmd, sizeof(cmd), "trust %s", mac);
    btctl(cmd, NULL, 0);

    snprintf(cmd, sizeof(cmd), "connect %s", mac);
    int rc = btctl(cmd, NULL, 0);

    if (rc == 0)
    {
        /* Find the device and check if it's audio-capable */
        for (size_t i = 0; i < g_device_count; i++)
        {
            if (strcmp(g_devices[i].mac, mac) == 0)
            {
                g_devices[i].connected = 1;
                if (g_devices[i].audio_capable)
                    asound_set_bt(mac);
                break;
            }
        }
    }
    return rc;
}

int bluetooth_service_disconnect(const char *mac)
{
    if (!mac)
        return -1;
    char cmd[64];
    snprintf(cmd, sizeof(cmd), "disconnect %s", mac);
    int rc = btctl(cmd, NULL, 0);

    if (rc == 0)
    {
        for (size_t i = 0; i < g_device_count; i++)
        {
            if (strcmp(g_devices[i].mac, mac) == 0)
            {
                g_devices[i].connected = 0;
                break;
            }
        }
        asound_restore_usb();
    }
    return rc;
}

int bluetooth_service_remove(const char *mac)
{
    if (!mac)
        return -1;
    char cmd[64];
    snprintf(cmd, sizeof(cmd), "remove %s", mac);
    int rc = btctl(cmd, NULL, 0);

    if (rc == 0)
    {
        /* Remove from internal list */
        for (size_t i = 0; i < g_device_count; i++)
        {
            if (strcmp(g_devices[i].mac, mac) == 0)
            {
                if (g_devices[i].connected)
                    asound_restore_usb();
                /* Shift remaining entries down */
                for (size_t j = i; j + 1 < g_device_count; j++)
                    g_devices[j] = g_devices[j + 1];
                g_device_count--;
                break;
            }
        }
    }
    return rc;
}